# Generated by Django 5.1.4 on 2025-01-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="self_payer", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MediFoxUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("public", "Public"),
                            ("none", "Not Insured"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("birth_date", models.DateField(null=True)),
                (
                    "insurance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="chat.insurance"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("user_is_sender", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sender",
                        to="chat.medifoxuser",
                    ),
                ),
            ],
        ),
    ]
