# Generated by Django 5.1.4 on 2025-01-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="producer",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="medication",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
