# Generated by Django 5.1.4 on 2025-01-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_medication_producer_alter_medication_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                ("contact_email", models.EmailField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="medication",
            name="producer",
        ),
        migrations.AlterField(
            model_name="medication",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="medication",
            name="manufacturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pharmacy.manufacturer",
            ),
        ),
    ]
